# Import libraries

In [ ]:
#Here we want to understand which features are strongly associated to survived = yes. eg. if 1st class, Male->Yes OR female->yes
#Install 'mlxtend' Library if not installed already
!pip install mlxtend

In [1]:
import mlxtend

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
titanic=pd.read_csv("/content/Titanic.csv")
titanic

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     Class  Gender    Age Survived
0      3rd    Male  Child       No
1      3rd    Male  Child       No
2      3rd    Male  Child       No
3      3rd    Male  Child       No
4      3rd    Male  Child       No
...    ...     ...    ...      ...
2196  Crew  Female  Adult      Yes
2197  Crew  Female  Adult      Yes
2198  Crew  Female  Adult      Yes
2199  Crew  Female  Adult      Yes
2200  Crew  Female  Adult      Yes

[2201 rows x 4 columns]

In [7]:
titanic.shape

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(2201, 4)

In [8]:
titanic["Class"].value_counts()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Crew    885
3rd     706
1st     325
2nd     285
Name: Class, dtype: int64

In [9]:
titanic["Gender"].value_counts()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Male      1731
Female     470
Name: Gender, dtype: int64

In [10]:
titanic["Age"].value_counts()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Adult    2092
Child     109
Name: Age, dtype: int64

In [11]:
titanic["Survived"].value_counts()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

No     1490
Yes     711
Name: Survived, dtype: int64

# Pre-Processing

As the data is not in transaction formation We are using transaction Encoder

In [12]:
df=pd.get_dummies(titanic)
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,Class_1st,Class_2nd,Class_3rd,Class_Crew,Gender_Female,Gender_Male,Age_Adult,Age_Child,Survived_No,Survived_Yes
0,0,0,1,0,0,1,0,1,1,0
1,0,0,1,0,0,1,0,1,1,0
2,0,0,1,0,0,1,0,1,1,0
3,0,0,1,0,0,1,0,1,1,0
4,0,0,1,0,0,1,0,1,1,0

# Apriori Algorithm

In [13]:
frequent_itemsets=apriori(df,min_support=0.1, use_colnames=True) #df-dataframe, min_support default=0.5
# min_support is a float between 0 and 1 for minumum support of the itemsets returned.
# The support is computed as the fraction transactions_where_item(s)_occur / total_transactions.
frequent_itemsets # output is frequent itemsets: 1-item itemsets, 2-item itemsets etc. with min support criteria

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support                                           itemsets
0   0.147660                                        (Class_1st)
1   0.129487                                        (Class_2nd)
2   0.320763                                        (Class_3rd)
3   0.402090                                       (Class_Crew)
4   0.213539                                    (Gender_Female)
5   0.786461                                      (Gender_Male)
6   0.950477                                        (Age_Adult)
7   0.676965                                      (Survived_No)
8   0.323035                                     (Survived_Yes)
9   0.144934                             (Age_Adult, Class_1st)
10  0.118582                             (Class_2nd, Age_Adult)
11  0.231713                           (Class_3rd, Gender_Male)
12  0.284871                             (Class_3rd, Age_Adult)
13  0.239891                           (Class_3rd, Survived_No)
14  0.391640                          (Gender_Male, Class_Crew)
15  0.402090                            (Age_Adult, Class_Crew)
16  0.305770                          (Survived_No, Class_Crew)
17  0.193094                         (Age_Adult, Gender_Female)
18  0.156293                      (Gender_Female, Survived_Yes)
19  0.757383                           (Age_Adult, Gender_Male)
20  0.619718                         (Survived_No, Gender_Male)
21  0.166742                        (Gender_Male, Survived_Yes)
22  0.653339                           (Age_Adult, Survived_No)
23  0.297138                          (Age_Adult, Survived_Yes)
24  0.209905                (Class_3rd, Age_Adult, Gender_Male)
25  0.191731              (Class_3rd, Survived_No, Gender_Male)
26  0.216265                (Class_3rd, Age_Adult, Survived_No)
27  0.391640               (Age_Adult, Gender_Male, Class_Crew)
28  0.304407             (Survived_No, Gender_Male, Class_Crew)
29  0.305770               (Age_Adult, Survived_No, Class_Crew)
30  0.143571           (Age_Adult, Gender_Female, Survived_Yes)
31  0.603816              (Age_Adult, Survived_No, Gender_Male)
32  0.153567             (Gender_Male, Survived_Yes, Age_Adult)
33  0.175829   (Class_3rd, Age_Adult, Survived_No, Gender_Male)
34  0.304407  (Age_Adult, Survived_No, Gender_Male, Class_Crew)

In [14]:
rules=association_rules(frequent_itemsets,metric="lift",min_threshold=0.7)  # min_threshold is Confidence
rules  # http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/
rules.sort_values("lift",ascending=False)[0:20]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
64,"(Age_Adult, Gender_Female)",(Survived_Yes),0.193094,0.323035,0.143571,0.743529,2.301699,0.081195,2.639542,0.700873
69,(Survived_Yes),"(Age_Adult, Gender_Female)",0.323035,0.193094,0.143571,0.444444,2.301699,0.081195,1.452431,0.835403
18,(Gender_Female),(Survived_Yes),0.213539,0.323035,0.156293,0.731915,2.265745,0.087312,2.525187,0.710327
19,(Survived_Yes),(Gender_Female),0.323035,0.213539,0.156293,0.483826,2.265745,0.087312,1.523634,0.825219
68,(Gender_Female),"(Age_Adult, Survived_Yes)",0.213539,0.297138,0.143571,0.672340,2.262724,0.080121,2.145099,0.709577
65,"(Age_Adult, Survived_Yes)",(Gender_Female),0.297138,0.213539,0.143571,0.483180,2.262724,0.080121,1.521732,0.793974
100,"(Survived_No, Class_Crew)","(Age_Adult, Gender_Male)",0.305770,0.757383,0.304407,0.995542,1.314450,0.072822,54.427079,0.344592
97,"(Age_Adult, Gender_Male)","(Survived_No, Class_Crew)",0.757383,0.305770,0.304407,0.401920,1.314450,0.072822,1.160764,0.986022
51,(Class_Crew),"(Age_Adult, Gender_Male)",0.402090,0.757383,0.391640,0.974011,1.286022,0.087104,9.335480,0.371976
46,"(Age_Adult, Gender_Male)",(Class_Crew),0.757383,0.402090,0.391640,0.517097,1.286022,0.087104,1.238157,0.916706
53,"(Survived_No, Class_Crew)",(Gender_Male),0.305770,0.786461,0.304407,0.995542,1.265851,0.063931,47.903983,0.302519
104,(Gender_Male),"(Age_Adult, Survived_No, Class_Crew)",0.786461,0.305770,0.304407,0.387060,1.265851,0.063931,1.132622,0.983509
93,"(Age_Adult, Survived_No, Class_Crew)",(Gender_Male),0.305770,0.786461,0.304407,0.995542,1.265851,0.063931,47.903983,0.302519
56,(Gender_Male),"(Survived_No, Class_Crew)",0.786461,0.305770,0.304407,0.387060,1.265851,0.063931,1.132622,0.983509
105,(Class_Crew),"(Age_Adult, Survived_No, Gender_Male)",0.402090,0.603816,0.304407,0.757062,1.253795,0.061619,1.630802,0.338549
92,"(Age_Adult, Survived_No, Gender_Male)",(Class_Crew),0.603816,0.402090,0.304407,0.504138,1.253795,0.061619,1.205800,0.510929
47,"(Age_Adult, Class_Crew)",(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,0.075412,8.216621,0.322047
50,(Gender_Male),"(Age_Adult, Class_Crew)",0.786461,0.402090,0.391640,0.497978,1.238474,0.075412,1.191004,0.901730
10,(Gender_Male),(Class_Crew),0.786461,0.402090,0.391640,0.497978,1.238474,0.075412,1.191004,0.901730
11,(Class_Crew),(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,0.075412,8.216621,0.322047

In [15]:
rules[rules.lift>1]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Age_Adult),(Class_1st),0.950477,0.147660,0.144934,0.152486,1.032680,0.004587,1.005694,0.639010
1,(Class_1st),(Age_Adult),0.147660,0.950477,0.144934,0.981538,1.032680,0.004587,2.682493,0.037128
8,(Class_3rd),(Survived_No),0.320763,0.676965,0.239891,0.747875,1.104747,0.022745,1.281251,0.139592
9,(Survived_No),(Class_3rd),0.676965,0.320763,0.239891,0.354362,1.104747,0.022745,1.052040,0.293515
10,(Gender_Male),(Class_Crew),0.786461,0.402090,0.391640,0.497978,1.238474,0.075412,1.191004,0.901730
...,...,...,...,...,...,...,...,...,...,...
101,"(Gender_Male, Class_Crew)","(Age_Adult, Survived_No)",0.391640,0.653339,0.304407,0.777262,1.189676,0.048533,1.556362,0.262074
102,(Age_Adult),"(Survived_No, Gender_Male, Class_Crew)",0.950477,0.304407,0.304407,0.320268,1.052103,0.015075,1.023334,1.000000
103,(Survived_No),"(Age_Adult, Gender_Male, Class_Crew)",0.676965,0.391640,0.304407,0.449664,1.148157,0.039280,1.105434,0.399458
104,(Gender_Male),"(Age_Adult, Survived_No, Class_Crew)",0.786461,0.305770,0.304407,0.387060,1.265851,0.063931,1.132622,0.983509
105,(Class_Crew),"(Age_Adult, Survived_No, Gender_Male)",0.402090,0.603816,0.304407,0.757062,1.253795,0.061619,1.630802,0.338549

# Another Example with Retail_Dataset

In [16]:
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [17]:
df = pd.read_csv('/content/retail_dataset.csv')
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

        0       1     2       3       4       5       6
0   Bread    Wine  Eggs    Meat  Cheese  Pencil  Diaper
1   Bread  Cheese  Meat  Diaper    Wine    Milk  Pencil
2  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
3  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
4    Meat  Pencil  Wine     NaN     NaN     NaN     NaN

In [18]:
df.shape

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(315, 7)

In [19]:
# Find unique values of column index 0.
items = (df['0'].unique())
items

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

array(['Bread', 'Cheese', 'Meat', 'Eggs', 'Wine', 'Bagel', 'Pencil',
       'Diaper', 'Milk'], dtype=object)

In [20]:
# One-hot encoding
encoded_vals = []
for index, row in df.iterrows(): # iterrows() returns index and content for each row
    labels = {}
    uncommons = list(set(items) - set(row))#total 9 items (Bagel,Milk,...,pencil) - items present in row = Bagel, Milk (for 1st row these 2 items are not present)
    commons = list(set(items).intersection(row))# common items
    for uc in uncommons:
        labels[uc] = 0 # assign 0 to uncommon items
    for com in commons:
        labels[com] = 1# assign 1 to common items
    encoded_vals.append(labels)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [21]:
encoded_vals

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

[{'Bagel': 0,
  'Milk': 0,
  'Wine': 1,
  'Meat': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1},
 {'Bagel': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1},
 {'Pencil': 0,
  'Bagel': 0,
  'Diaper': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1},
 {'Pencil': 0,
  'Bagel': 0,
  'Diaper': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1},
 {'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Wine': 1,
  'Pencil': 1,
  'Meat': 1},
 {'Meat': 0,
  'Cheese': 0,
  'Wine': 1,
  'Milk': 1,
  'Eggs': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Meat': 0,
  'Milk': 0,
  'Bread': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Wine': 1,
  'Pencil': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Meat': 0,
  'Cheese': 0,
  'Eggs': 0,
  'Milk': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Pencil': 0,
  'Meat': 0,
  'Bagel': 0,
  'Wine': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Milk': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Pencil': 0,
  'Bagel': 0,
  'Diaper': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1},
 {'Pencil': 0,
  'Cheese': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Bread': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Milk': 0,
  'Cheese': 0,
  'Eggs': 0,
  'Meat': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Meat': 1,
  'Bagel': 1,
  'Milk': 1,
  'Cheese': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Bread': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bread': 0,
  'Pencil': 1,
  'Bagel': 1,
  'Diaper': 1},
 {'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Meat': 1,
  'Bread': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bread': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Diaper': 1},
 {'Wine': 0,
  'Pencil': 0,
  'Milk': 0,
  'Meat': 1,
  'Eggs': 1,
  'Bread': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Pencil': 1,
  'Bread': 1,
  'Meat': 1,
  'Cheese': 1},
 {'Bagel': 0,
  'Diaper': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Bread': 1,
  'Cheese': 1,
  'Pencil': 1},
 {'Wine': 0,
  'Pencil': 0,
  'Milk': 0,
  'Bread': 0,
  'Meat': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Bread': 0,
  'Bagel': 0,
  'Milk': 0,
  'Cheese': 0,
  'Wine': 1,
  'Meat': 1,
  'Eggs': 1,
  'Diaper': 1,
  'Pencil': 1},
 {'Wine': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Meat': 1,
  'Milk': 1,
  'Bread': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bread': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Pencil': 1},
 {'Pencil': 0,
  'Bagel': 0,
  'Diaper': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1},
 {'Bagel': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Bread': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Pencil': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Bread': 1},
 {'Wine': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Diaper': 1},
 {'Pencil': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Wine': 1,
  'Bread': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Bread': 1,
  'Milk': 1,
  'Cheese': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Pencil': 0,
  'Milk': 0,
  'Cheese': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Bread': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Pencil': 0,
  'Meat': 0,
  'Bagel': 0,
  'Eggs': 0,
  'Wine': 1,
  'Milk': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Eggs': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1},
 {'Meat': 0,
  'Diaper': 0,
  'Wine': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Eggs': 1},
 {'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Wine': 1,
  'Meat': 1,
  'Diaper': 1},
 {'Pencil': 0,
  'Meat': 0,
  'Wine': 1,
  'Milk': 1,
  'Eggs': 1,
  'Bread': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Meat': 0,
  'Milk': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Wine': 1,
  'Eggs': 1},
 {'Pencil': 0,
  'Bagel': 0,
  'Diaper': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1},
 {'Meat': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Wine': 1,
  'Milk': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bread': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Diaper': 1},
 {'Pencil': 0,
  'Meat': 0,
  'Cheese': 0,
  'Eggs': 0,
  'Wine': 1,
  'Milk': 1,
  'Bread': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Pencil': 0,
  'Bagel': 0,
  'Diaper': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1},
 {'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Pencil': 0,
  'Bagel': 0,
  'Milk': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Bread': 1,
  'Cheese': 1,
  'Diaper': 1},
 {'Meat': 0,
  'Bread': 0,
  'Bagel': 0,
  'Wine': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Pencil': 1},
 {'Pencil': 0,
  'Bagel': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Bread': 0,
  'Cheese': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Diaper': 1,
  'Eggs': 1},
 {'Pencil': 0,
  'Bagel': 0,
  'Diaper': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1},
 {'Milk': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Bread': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 1,
  'Bagel': 1,
  'Milk': 1,
  'Cheese': 1},
 {'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Wine': 1,
  'Meat': 1,
  'Diaper': 1,
  'Cheese': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Bagel': 0,
  'Cheese': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1},
 {'Meat': 0,
  'Milk': 0,
  'Bread': 0,
  'Bagel': 0,
  'Wine': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Pencil': 1},
 {'Wine': 0,
  'Meat': 0,
  'Bagel': 0,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Pencil': 1,
  'Milk': 1,
  'Cheese': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Bread': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  'Meat': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Pencil': 0,
  'Diaper': 1,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Bread': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Meat': 0,
  'Bread': 0,
  'Cheese': 0,
  'Bagel': 0,
  'Pencil': 1,
  'Diaper': 1,
  'Milk': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Pencil': 1,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1},
 {'Wine': 0,
  'Pencil': 0,
  'Milk': 0,
  'Eggs': 0,
  'Meat': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Meat': 0,
  'Milk': 0,
  'Wine': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bread': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Diaper': 1},
 {'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Milk': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Pencil': 1,
  'Bread': 1},
 {'Meat': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Wine': 1,
  'Milk': 1,
  'Cheese': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Cheese': 1},
 {'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Bagel': 0,
  'Wine': 1,
  'Pencil': 1,
  'Diaper': 1},
 {'Wine': 0,
  'Milk': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 1,
  'Meat': 1,
  'Bagel': 1},
 {'Pencil': 0,
  'Diaper': 0,
  'Milk': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bagel': 1},
 {'Pencil': 0,
  'Diaper': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Bread': 1,
  'Bagel': 1},
 {'Diaper': 0,
  'Bagel': 0,
  'Milk': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Bread': 1,
  'Cheese': 1,
  'Pencil': 1},
 {'Diaper': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Bread': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Meat': 0,
  'Bread': 0,
  'Eggs': 0,
  'Wine': 1,
  'Milk': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Milk': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Pencil': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bread': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Pencil': 1},
 {'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Wine': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Bread': 1},
 {'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Wine': 1,
  'Pencil': 1,
  'Bagel': 1,
  'Meat': 1},
 {'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Wine': 1,
  'Bread': 1},
 {'Meat': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Wine': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Pencil': 1},
 {'Wine': 0,
  'Pencil': 0,
  'Diaper': 0,
  'Bread': 0,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Milk': 0,
  'Bread': 0,
  'Cheese': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Wine': 1,
  'Meat': 1,
  'Diaper': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Diaper': 1},
 {'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Wine': 1,
  'Pencil': 1,
  'Milk': 1,
  'Bread': 1},
 {'Diaper': 0,
  'Cheese': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Bread': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Pencil': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Pencil': 0,
  'Meat': 0,
  'Bread': 0,
  'Eggs': 0,
  'Wine': 1,
  'Milk': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bread': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Diaper': 1},
 {'Wine': 0,
  'Diaper': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  'Bread': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Pencil': 1,
  'Meat': 1,
  'Milk': 1},
 {'Bagel': 0,
  'Milk': 0,
  'Wine': 1,
  'Meat': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1},
 {'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Cheese': 1},
 {'Pencil': 0,
  'Diaper': 0,
  'Milk': 0,
  'Cheese': 0,
  'Wine': 1,
  'Meat': 1,
  'Eggs': 1,
  'Bread': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Cheese': 1},
 {'Bread': 0,
  'Milk': 0,
  'Cheese': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Pencil': 1,
  'Milk': 1},
 {'Bread': 0,
  'Meat': 0,
  'Milk': 0,
  'Cheese': 0,
  'Wine': 1,
  'Eggs': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Bagel': 0,
  'Diaper': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Pencil': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Pencil': 1,
  'Bread': 1},
 {'Meat': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Wine': 1,
  'Bagel': 1,
  'Milk': 1,
  'Eggs': 1},
 {'Diaper': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Milk': 1,
  'Cheese': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bagel': 0,
  'Pencil': 1,
  'Diaper': 1,
  'Bread': 1,
  'Milk': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1,
  'Milk': 1,
  'Bread': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bread': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Diaper': 1},
 {'Pencil': 0,
  'Milk': 0,
  'Cheese': 0,
  'Eggs': 0,
  'Wine': 1,
  'Meat': 1,
  'Bread': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 1},
 {'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Wine': 1,
  'Diaper': 1},
 {'Wine': 0,
  'Pencil': 0,
  'Milk': 0,
  'Bread': 0,
  'Meat': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 1,
  'Bagel': 1,
  'Bread': 1,
  'Eggs': 1},
 {'Bagel': 0,
  'Diaper': 0,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Bread': 1,
  'Cheese': 1,
  'Pencil': 1},
 {'Wine': 0,
  'Milk': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Pencil': 1,
  'Meat': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Diaper': 0,
  'Milk': 0,
  'Meat': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  'Milk': 1,
  'Bread': 1,
  'Eggs': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Milk': 1},
 {'Wine': 0,
  'Diaper': 0,
  'Milk': 0,
  'Eggs': 0,
  'Meat': 1,
  'Cheese': 1,
  'Bread': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Meat': 0,
  'Milk': 0,
  'Cheese': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Wine': 1,
  'Diaper': 1,
  'Bread': 1,
  'Eggs': 1},
 {'Pencil': 0,
  'Diaper': 0,
  'Milk': 0,
  'Wine': 1,
  'Meat': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Eggs': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Bread': 1,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1},
 {'Wine': 0,
  'Bagel': 0,
  'Diaper': 0,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Bread': 1,
  'Cheese': 1,
  'Pencil': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Bread': 1},
 {'Wine': 0,
  'Cheese': 0,
  'Meat': 1,
  'Milk': 1,
  'Eggs': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Bread': 0,
  'Cheese': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Diaper': 1,
  'Milk': 1},
 {'Pencil': 0,
  'Milk': 0,
  'Wine': 1,
  'Meat': 1,
  'Eggs': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Eggs': 0,
  'Milk': 1,
  'Cheese': 1,
  'Bread': 1,
  'Diaper': 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 0,
  'Bread': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Diaper': 1},
 {'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Meat': 1,
  'Milk': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Milk': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Wine': 1,
  'Meat': 1,
  'Cheese': 1,
  'Bagel': 1},
 {'Wine': 0,
  'Meat': 0,
  'Bread': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Milk': 1,
  'Diaper': 1,
  'Cheese': 1,
  'Eggs': 1},
 {'Diaper': 0,
  'Bagel': 0,
  'Milk': 0,
  'Bread': 0,
  'Wine': 1,
  'Meat': 1,

In [22]:
ohe_df = pd.DataFrame(encoded_vals)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [23]:
ohe_df

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     Bagel  Milk  Wine  Meat  Eggs  Cheese  Bread  Diaper  Pencil
0        0     0     1     1     1       1      1       1       1
1        0     1     1     1     0       1      1       1       1
2        0     1     1     1     1       1      0       0       0
3        0     1     1     1     1       1      0       0       0
4        0     0     1     1     0       0      0       0       1
..     ...   ...   ...   ...   ...     ...    ...     ...     ...
310      0     0     0     0     1       1      1       0       0
311      0     1     0     1     0       0      0       0       1
312      0     0     1     1     1       1      1       1       1
313      0     0     0     1     0       1      0       0       0
314      1     0     1     1     1       0      1       0       0

[315 rows x 9 columns]

In [24]:
freq_items = apriori(ohe_df, min_support = 0.2, use_colnames = True)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [25]:
freq_items

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     support              itemsets
0   0.425397               (Bagel)
1   0.501587                (Milk)
2   0.438095                (Wine)
3   0.476190                (Meat)
4   0.438095                (Eggs)
5   0.501587              (Cheese)
6   0.504762               (Bread)
7   0.406349              (Diaper)
8   0.361905              (Pencil)
9   0.225397         (Bagel, Milk)
10  0.279365        (Bagel, Bread)
11  0.219048          (Wine, Milk)
12  0.244444          (Meat, Milk)
13  0.244444          (Milk, Eggs)
14  0.304762        (Milk, Cheese)
15  0.279365         (Milk, Bread)
16  0.250794          (Wine, Meat)
17  0.241270          (Wine, Eggs)
18  0.269841        (Wine, Cheese)
19  0.244444         (Wine, Bread)
20  0.234921        (Wine, Diaper)
21  0.200000        (Wine, Pencil)
22  0.266667          (Meat, Eggs)
23  0.323810        (Meat, Cheese)
24  0.206349         (Meat, Bread)
25  0.298413        (Cheese, Eggs)
26  0.238095       (Bread, Cheese)
27  0.200000      (Diaper, Cheese)
28  0.200000      (Pencil, Cheese)
29  0.231746       (Diaper, Bread)
30  0.200000       (Pencil, Bread)
31  0.203175  (Meat, Milk, Cheese)
32  0.215873  (Meat, Cheese, Eggs)

In [26]:
asso_rules=association_rules(freq_items, metric = "confidence", min_threshold = 0.6) # can use metric as lift

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [27]:
asso_rules

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Bagel),(Bread),0.425397,0.504762,0.279365,0.656716,1.301042,0.064641,1.442650,0.402687
1,(Milk),(Cheese),0.501587,0.501587,0.304762,0.607595,1.211344,0.053172,1.270148,0.350053
2,(Cheese),(Milk),0.501587,0.501587,0.304762,0.607595,1.211344,0.053172,1.270148,0.350053
3,(Wine),(Cheese),0.438095,0.501587,0.269841,0.615942,1.227986,0.050098,1.297754,0.330409
4,(Eggs),(Meat),0.438095,0.476190,0.266667,0.608696,1.278261,0.058050,1.338624,0.387409
5,(Meat),(Cheese),0.476190,0.501587,0.323810,0.680000,1.355696,0.084958,1.557540,0.500891
6,(Cheese),(Meat),0.501587,0.476190,0.323810,0.645570,1.355696,0.084958,1.477891,0.526414
7,(Eggs),(Cheese),0.438095,0.501587,0.298413,0.681159,1.358008,0.078670,1.563203,0.469167
8,"(Meat, Milk)",(Cheese),0.244444,0.501587,0.203175,0.831169,1.657077,0.080564,2.952137,0.524816
9,"(Meat, Cheese)",(Milk),0.323810,0.501587,0.203175,0.627451,1.250931,0.040756,1.337845,0.296655
10,"(Milk, Cheese)",(Meat),0.304762,0.476190,0.203175,0.666667,1.400000,0.058050,1.571429,0.410959
11,"(Meat, Cheese)",(Eggs),0.323810,0.438095,0.215873,0.666667,1.521739,0.074014,1.685714,0.507042
12,"(Meat, Eggs)",(Cheese),0.266667,0.501587,0.215873,0.809524,1.613924,0.082116,2.616667,0.518717
13,"(Cheese, Eggs)",(Meat),0.298413,0.476190,0.215873,0.723404,1.519149,0.073772,1.893773,0.487091

In [28]:
asso_rules.sort_values('confidence',ascending = False) # can sort as lift value

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
8,"(Meat, Milk)",(Cheese),0.244444,0.501587,0.203175,0.831169,1.657077,0.080564,2.952137,0.524816
12,"(Meat, Eggs)",(Cheese),0.266667,0.501587,0.215873,0.809524,1.613924,0.082116,2.616667,0.518717
13,"(Cheese, Eggs)",(Meat),0.298413,0.476190,0.215873,0.723404,1.519149,0.073772,1.893773,0.487091
7,(Eggs),(Cheese),0.438095,0.501587,0.298413,0.681159,1.358008,0.078670,1.563203,0.469167
5,(Meat),(Cheese),0.476190,0.501587,0.323810,0.680000,1.355696,0.084958,1.557540,0.500891
10,"(Milk, Cheese)",(Meat),0.304762,0.476190,0.203175,0.666667,1.400000,0.058050,1.571429,0.410959
11,"(Meat, Cheese)",(Eggs),0.323810,0.438095,0.215873,0.666667,1.521739,0.074014,1.685714,0.507042
0,(Bagel),(Bread),0.425397,0.504762,0.279365,0.656716,1.301042,0.064641,1.442650,0.402687
6,(Cheese),(Meat),0.501587,0.476190,0.323810,0.645570,1.355696,0.084958,1.477891,0.526414
9,"(Meat, Cheese)",(Milk),0.323810,0.501587,0.203175,0.627451,1.250931,0.040756,1.337845,0.296655
3,(Wine),(Cheese),0.438095,0.501587,0.269841,0.615942,1.227986,0.050098,1.297754,0.330409
4,(Eggs),(Meat),0.438095,0.476190,0.266667,0.608696,1.278261,0.058050,1.338624,0.387409
1,(Milk),(Cheese),0.501587,0.501587,0.304762,0.607595,1.211344,0.053172,1.270148,0.350053
2,(Cheese),(Milk),0.501587,0.501587,0.304762,0.607595,1.211344,0.053172,1.270148,0.350053